# This is a basic workflow to help you get started with Actions

name: Deploy To Naver Cloud Platform

# Controls when the workflow will run
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

        # 2. Java 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # 3. Gradle 의존성 캐싱
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
            
       # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootjar -x test

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bomul:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/bomul:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/bomul:latest

      # 6. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Docker 이미지 푸시
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bomul:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bomul:latest
        
